python exp_airfoil.py \
--gpu 3 \
--model SAOT_Structured_Mesh_2D \
--n-hidden 256 \
--n-heads 8 \
--n-layers 5 \
--lr 0.001 \
--max_grad_norm 0.1 \
--batch-size 2 \
--slice_num 64 \
--unified_pos 0 \
--ref 8 \
--eval 0 \
--save_name airfoil_SAOT
