python exp_elas.py \
--gpu 3 \
--model SAOT_Irregular_Mesh \
--n-hidden 144 \
--n-heads 8 \
--n-layers 10 \
--mlp_ratio 1 \
--lr 0.001 \
--max_grad_norm 0.1 \
--batch-size 8 \
--slice_num 64 \
--unified_pos 0 \
--ref 8 \
--eval 0 \
--save_name elas_SAOT